title: Sportfreunde 02 Reutlingen e.V
url: https://kolpinghaus-reutlingen.de

destination: _site

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

include:
  - .htaccess
  - "*_*.jpg"

